<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="SDS322E" />


<title>Project 1: Wrangling, Exploration, Visualization</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>





<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Site</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="portfolio.html">Portfolio</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="mailto:&lt;your@email.com&gt;">
    <span class="fas fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://github.com/USERNAME/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://linkedin.com/USERNAME">
    <span class="fab fa-linkedin fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Project 1: Wrangling, Exploration, Visualization</h1>
<h4 class="author">SDS322E</h4>

</div>


<div id="data-wrangling-exploration-visualization" class="section level2">
<h2>Data Wrangling, Exploration, Visualization</h2>
<div id="abigail-tovar" class="section level3">
<h3>Abigail Tovar</h3>
<div id="introduction" class="section level4">
<h4>Introduction</h4>
<p>This project analyzes local house prices around Austin Texas. Austin is one of the fastest growing cities in the nation proving itself to be a desirable spot for travel, leisure, and work in the past decade. The second dataset I analyzed for the project contains data of crime in Austin in 2018. This phenomenon is interesting to me as I have lived here for many years so seeing the transition within real estate from gentrification, and the implications of these changing demographics in certain areas over others in terms of crime rate is of great interest to me. Furthermore, there was a good amount of quality data that was readily available and highly relatable for these topics. I acquired the two datasets from Kaggle.com, as well as, the official website for the city of Austin government.</p>
</div>
<div id="tidying-reshaping" class="section level4">
<h4>Tidying: Reshaping</h4>
<p>If your datasets are tidy already, demonstrate that you can reshape data with pivot wider/longer here (e.g., untidy and then retidy). Alternatively, it may be easier to wait until the wrangling section so you can reshape your summary statistics. Note here if you are going to do this.</p>
<pre class="r"><code># Will reshape later</code></pre>
</div>
<div id="joiningmerging" class="section level4">
<h4>Joining/Merging</h4>
<pre class="r"><code>library(tidyverse)
data_1 &lt;- read_csv(&quot;Crime_Reports_2018.csv&quot;)
data_2 &lt;- read_csv(&quot;austinHousingData.csv&quot;)
merged_data &lt;- data_1 %&gt;% inner_join(data_2, by = c(`Zip Code` = &quot;zipcode&quot;))
head(merged_data)</code></pre>
<pre><code>## # A tibble: 6 x 73
##   `Incident Numbe… `Highest Offens… `Highest Offens… `Family Violenc…
##              &lt;dbl&gt; &lt;chr&gt;                       &lt;dbl&gt; &lt;chr&gt;           
## 1        201811444 FAMILY DISTURBA…             3400 N               
## 2        201811444 FAMILY DISTURBA…             3400 N               
## 3        201811444 FAMILY DISTURBA…             3400 N               
## 4        201811444 FAMILY DISTURBA…             3400 N               
## 5        201811444 FAMILY DISTURBA…             3400 N               
## 6        201811444 FAMILY DISTURBA…             3400 N               
## # … with 69 more variables: `Occurred Date Time` &lt;chr&gt;, `Occurred Date` &lt;chr&gt;,
## #   `Occurred Time` &lt;dbl&gt;, `Report Date Time` &lt;chr&gt;, `Report Date` &lt;chr&gt;,
## #   `Report Time` &lt;dbl&gt;, `Location Type` &lt;chr&gt;, Address &lt;chr&gt;, `Zip
## #   Code` &lt;dbl&gt;, `Council District` &lt;dbl&gt;, `APD Sector` &lt;chr&gt;, `APD
## #   District` &lt;chr&gt;, PRA &lt;dbl&gt;, `Census Tract` &lt;dbl&gt;, `Clearance Status` &lt;chr&gt;,
## #   `Clearance Date` &lt;chr&gt;, `UCR Category` &lt;chr&gt;, `Category Description` &lt;chr&gt;,
## #   `X-coordinate` &lt;dbl&gt;, `Y-coordinate` &lt;dbl&gt;, Latitude &lt;dbl&gt;,
## #   Longitude &lt;dbl&gt;, Location &lt;chr&gt;, zpid &lt;dbl&gt;, city &lt;chr&gt;,
## #   streetAddress &lt;chr&gt;, description &lt;chr&gt;, latitude &lt;dbl&gt;, longitude &lt;dbl&gt;,
## #   propertyTaxRate &lt;dbl&gt;, garageSpaces &lt;dbl&gt;, hasAssociation &lt;lgl&gt;,
## #   hasCooling &lt;lgl&gt;, hasGarage &lt;lgl&gt;, hasHeating &lt;lgl&gt;, hasSpa &lt;lgl&gt;,
## #   hasView &lt;lgl&gt;, homeType &lt;chr&gt;, parkingSpaces &lt;dbl&gt;, yearBuilt &lt;dbl&gt;,
## #   latestPrice &lt;dbl&gt;, numPriceChanges &lt;dbl&gt;, latest_saledate &lt;date&gt;,
## #   latest_salemonth &lt;dbl&gt;, latest_saleyear &lt;dbl&gt;, latestPriceSource &lt;chr&gt;,
## #   numOfPhotos &lt;dbl&gt;, numOfAccessibilityFeatures &lt;dbl&gt;, numOfAppliances &lt;dbl&gt;,
## #   numOfParkingFeatures &lt;dbl&gt;, numOfPatioAndPorchFeatures &lt;dbl&gt;,
## #   numOfSecurityFeatures &lt;dbl&gt;, numOfWaterfrontFeatures &lt;dbl&gt;,
## #   numOfWindowFeatures &lt;dbl&gt;, numOfCommunityFeatures &lt;dbl&gt;, lotSizeSqFt &lt;dbl&gt;,
## #   livingAreaSqFt &lt;dbl&gt;, numOfPrimarySchools &lt;dbl&gt;,
## #   numOfElementarySchools &lt;dbl&gt;, numOfMiddleSchools &lt;dbl&gt;,
## #   numOfHighSchools &lt;dbl&gt;, avgSchoolDistance &lt;dbl&gt;, avgSchoolRating &lt;dbl&gt;,
## #   avgSchoolSize &lt;dbl&gt;, MedianStudentsPerTeacher &lt;dbl&gt;, numOfBathrooms &lt;dbl&gt;,
## #   numOfBedrooms &lt;dbl&gt;, numOfStories &lt;dbl&gt;, homeImage &lt;chr&gt;</code></pre>
<p>I performed an inner_join on the datasets because I wanted to preserve the data that was in the second data set, without dropping what was not in the first data set. I joined based on the zipcode for each area and eventually I figured it help me to visualize the distribution of prices in the area. After joining, the joined data set had 64 variables, and 43,141,748 objects. The crime dataset had 102446 rows and 27 columns, 26 of which were unique in the crime dataset and 47 variables 46 of which were unique and 15,318 objects in the “Austin Housing dataset”.</p>
</div>
<div id="wrangling" class="section level4">
<h4>Wrangling</h4>
<pre class="r"><code>library(tidyverse)

merged_data_3 &lt;- merged_data %&gt;% distinct(zpid, .keep_all = TRUE)
merged_data_3 %&gt;% arrange(desc(latestPrice))</code></pre>
<pre><code>## # A tibble: 15,126 x 73
##    `Incident Numbe… `Highest Offens… `Highest Offens… `Family Violenc…
##               &lt;dbl&gt; &lt;chr&gt;                       &lt;dbl&gt; &lt;chr&gt;           
##  1      20185003559 THEFT                         600 N               
##  2        201811457 DATING DISTURBA…             2400 N               
##  3       2018820828 VIOL CITY ORDIN…             3299 N               
##  4       2018820828 VIOL CITY ORDIN…             3299 N               
##  5        201811457 DATING DISTURBA…             2400 N               
##  6        201811457 DATING DISTURBA…             2400 N               
##  7        201811450 THEFT                         600 N               
##  8        201811457 DATING DISTURBA…             2400 N               
##  9        201811450 THEFT                         600 N               
## 10      20185003559 THEFT                         600 N               
## # … with 15,116 more rows, and 69 more variables: `Occurred Date Time` &lt;chr&gt;,
## #   `Occurred Date` &lt;chr&gt;, `Occurred Time` &lt;dbl&gt;, `Report Date Time` &lt;chr&gt;,
## #   `Report Date` &lt;chr&gt;, `Report Time` &lt;dbl&gt;, `Location Type` &lt;chr&gt;,
## #   Address &lt;chr&gt;, `Zip Code` &lt;dbl&gt;, `Council District` &lt;dbl&gt;, `APD
## #   Sector` &lt;chr&gt;, `APD District` &lt;chr&gt;, PRA &lt;dbl&gt;, `Census Tract` &lt;dbl&gt;,
## #   `Clearance Status` &lt;chr&gt;, `Clearance Date` &lt;chr&gt;, `UCR Category` &lt;chr&gt;,
## #   `Category Description` &lt;chr&gt;, `X-coordinate` &lt;dbl&gt;, `Y-coordinate` &lt;dbl&gt;,
## #   Latitude &lt;dbl&gt;, Longitude &lt;dbl&gt;, Location &lt;chr&gt;, zpid &lt;dbl&gt;, city &lt;chr&gt;,
## #   streetAddress &lt;chr&gt;, description &lt;chr&gt;, latitude &lt;dbl&gt;, longitude &lt;dbl&gt;,
## #   propertyTaxRate &lt;dbl&gt;, garageSpaces &lt;dbl&gt;, hasAssociation &lt;lgl&gt;,
## #   hasCooling &lt;lgl&gt;, hasGarage &lt;lgl&gt;, hasHeating &lt;lgl&gt;, hasSpa &lt;lgl&gt;,
## #   hasView &lt;lgl&gt;, homeType &lt;chr&gt;, parkingSpaces &lt;dbl&gt;, yearBuilt &lt;dbl&gt;,
## #   latestPrice &lt;dbl&gt;, numPriceChanges &lt;dbl&gt;, latest_saledate &lt;date&gt;,
## #   latest_salemonth &lt;dbl&gt;, latest_saleyear &lt;dbl&gt;, latestPriceSource &lt;chr&gt;,
## #   numOfPhotos &lt;dbl&gt;, numOfAccessibilityFeatures &lt;dbl&gt;, numOfAppliances &lt;dbl&gt;,
## #   numOfParkingFeatures &lt;dbl&gt;, numOfPatioAndPorchFeatures &lt;dbl&gt;,
## #   numOfSecurityFeatures &lt;dbl&gt;, numOfWaterfrontFeatures &lt;dbl&gt;,
## #   numOfWindowFeatures &lt;dbl&gt;, numOfCommunityFeatures &lt;dbl&gt;, lotSizeSqFt &lt;dbl&gt;,
## #   livingAreaSqFt &lt;dbl&gt;, numOfPrimarySchools &lt;dbl&gt;,
## #   numOfElementarySchools &lt;dbl&gt;, numOfMiddleSchools &lt;dbl&gt;,
## #   numOfHighSchools &lt;dbl&gt;, avgSchoolDistance &lt;dbl&gt;, avgSchoolRating &lt;dbl&gt;,
## #   avgSchoolSize &lt;dbl&gt;, MedianStudentsPerTeacher &lt;dbl&gt;, numOfBathrooms &lt;dbl&gt;,
## #   numOfBedrooms &lt;dbl&gt;, numOfStories &lt;dbl&gt;, homeImage &lt;chr&gt;</code></pre>
<pre class="r"><code>merged_data_3 %&gt;% group_by(`Zip Code`) %&gt;% summarize(average_price = mean(latestPrice)) %&gt;% 
    arrange(desc(average_price))</code></pre>
<pre><code>## # A tibble: 47 x 2
##    `Zip Code` average_price
##         &lt;dbl&gt;         &lt;dbl&gt;
##  1      78746      1422145.
##  2      78734      1390917.
##  3      78703      1192288.
##  4      78733      1061418.
##  5      78730      1020246.
##  6      78701       996475 
##  7      78735       977815.
##  8      78731       893546.
##  9      78704       839721.
## 10      78756       709739.
## # … with 37 more rows</code></pre>
<p>Before performing analysis on the data set I needed it to be tidy. Using tidy verse I dropped the rows which were unnecessary and removed deuplicates. Above I found the household that has the greatest listing price, then summarized by the zipcode to find the average price of the houses in this area. To find the most expensive area in Austin I grouped by zipcode and then summarized the columns in terms of average house prices in descending order, I also had to create a variable that stores the cumulative sum of houses for each zipcode. The result of was that the West Lake Hills or the ‘78746’ zipcode was the most expensive area in Austin, which would make sense as it has some of the best views in Austin, the average price for a listing here using my dataset was $1,422,145.10.</p>
<pre class="r"><code>crime_no_dup &lt;- merged_data %&gt;% distinct(Address, .keep_all = TRUE)

crime_no_dup %&gt;% group_by(`Zip Code`, `Highest Offense Description`) %&gt;% 
    summarize(count = n()) %&gt;% mutate(cm_crime = max(cumsum(count))) %&gt;% 
    arrange(desc(count))</code></pre>
<pre><code>## # A tibble: 3,837 x 4
## # Groups:   Zip Code [47]
##    `Zip Code` `Highest Offense Description` count cm_crime
##         &lt;dbl&gt; &lt;chr&gt;                         &lt;int&gt;    &lt;int&gt;
##  1      78745 BURGLARY OF VEHICLE             317     2640
##  2      78744 FAMILY DISTURBANCE              312     2231
##  3      78745 FAMILY DISTURBANCE              301     2640
##  4      78704 BURGLARY OF VEHICLE             292     2286
##  5      78702 BURGLARY OF VEHICLE             281     2216
##  6      78753 FAMILY DISTURBANCE              236     2169
##  7      78753 BURGLARY OF VEHICLE             209     2169
##  8      78704 THEFT                           197     2286
##  9      78758 BURGLARY OF VEHICLE             194     2186
## 10      78702 FAMILY DISTURBANCE              188     2216
## # … with 3,827 more rows</code></pre>
<p>I wanted to use my data to find the area which was most dangerous by zipcode, using the crime dataset and sorting by highest after calculating the cumulative sum, I got the zipcode of 78745, an area in South Austin. This stated the cumulative crime amount was 2640. I also was curoius to see the most common type of offense here which I found using the count feature, which reveals burglary of vehicle was most common with 317 reported crimes in 2018.</p>
<pre class="r"><code>crime_no_dup %&gt;% summarize(mean = mean(latestPrice, na.rm = TRUE), 
    quantile = quantile(latestPrice, probs = c(0.25, 0.75), na.rm = TRUE), 
    counts = n(), n_distinct = n_distinct(latestPrice), min = min(latestPrice, 
        na.rm = TRUE), max = max(latestPrice, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 2 x 6
##      mean quantile counts n_distinct    min     max
##     &lt;dbl&gt;    &lt;dbl&gt;  &lt;int&gt;      &lt;int&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 472152.   300000  35178         44 194800 4250000
## 2 472152.   525000  35178         44 194800 4250000</code></pre>
<pre class="r"><code>crime_no_dup %&gt;% na.omit() %&gt;% summarize(mean = mean(numPriceChanges, 
    na.rm = TRUE), sd = sd(numPriceChanges, na.rm = TRUE), quantile = quantile(numPriceChanges, 
    probs = c(0.25, 0.75), na.rm = TRUE), counts = n(), var = var(numPriceChanges, 
    na.rm = TRUE), n_distinct = n_distinct(numPriceChanges), 
    min = min(numPriceChanges, na.rm = TRUE), max = max(numPriceChanges, 
        na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 2 x 8
##    mean    sd quantile counts   var n_distinct   min   max
##   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;int&gt; &lt;dbl&gt;      &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  2.75  1.79        1   7942  3.20          9     1    13
## 2  2.75  1.79        3   7942  3.20          9     1    13</code></pre>
<pre class="r"><code>crime_no_dup %&gt;% na.omit() %&gt;% summarize(mean = mean(yearBuilt, 
    na.rm = TRUE), sd = sd(yearBuilt, na.rm = TRUE), quantile = quantile(yearBuilt, 
    probs = c(0.25, 0.75), na.rm = TRUE), counts = n(), var = var(yearBuilt, 
    na.rm = TRUE), n_distinct = n_distinct(yearBuilt), min = min(yearBuilt, 
    na.rm = TRUE), max = max(yearBuilt, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 2 x 8
##    mean    sd quantile counts   var n_distinct   min   max
##   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;int&gt; &lt;dbl&gt;      &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 1991.  21.7     1972   7942  473.         36  1923  2019
## 2 1991.  21.7     2009   7942  473.         36  1923  2019</code></pre>
<pre class="r"><code>crime_no_dup %&gt;% group_by() %&gt;% summarize(mean = mean(latest_saleyear, 
    na.rm = TRUE), sd = sd(latest_saleyear, na.rm = TRUE), quantile = quantile(latest_saleyear, 
    probs = c(0.25, 0.75), na.rm = TRUE), counts = n(), var = var(latest_saleyear, 
    na.rm = TRUE), n_distinct = n_distinct(yearBuilt), min = min(latest_saleyear, 
    na.rm = TRUE), max = max(latest_saleyear, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 2 x 8
##    mean    sd quantile counts   var n_distinct   min   max
##   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;int&gt; &lt;dbl&gt;      &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 2019. 0.769     2019  35178 0.591         37  2018  2020
## 2 2019. 0.769     2020  35178 0.591         37  2018  2020</code></pre>
<p>The summary statistics above I calculated for latest price, number of price changes, year built and sale year. The first for latest price showed that the mean price was $480,404.90 with a standard deviation of $273,209.20 which was fairly high I thought which could signify this value was spread over a wider range.The range of selling houses in terms of latest price is $300000 to $639,000. The cheapest house was $194,800 dollars which definitely speaks to how expensive Austin is, especially in this time of growth where prices for houses have surged. The max number of price changes was 13, and average was 2, which had expected to be higher, assuming that prices have been changing a lot in the market as it is experiencing a growth in demand. Year built for the average house in my dataset was 1990 and the standard deviation was 21 years.</p>
<pre class="r"><code>merged_data_3 %&gt;% filter(`Zip Code` == 78746) %&gt;% mutate(address_low = str_to_lower(Address)) %&gt;% 
    select(Address, address_low) %&gt;% head(5)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   Address                        address_low                   
##   &lt;chr&gt;                          &lt;chr&gt;                         
## 1 2901 S CAPITAL OF TEXAS HWY NB 2901 s capital of texas hwy nb
## 2 2901 S CAPITAL OF TEXAS HWY NB 2901 s capital of texas hwy nb
## 3 2901 S CAPITAL OF TEXAS HWY NB 2901 s capital of texas hwy nb
## 4 2901 S CAPITAL OF TEXAS HWY NB 2901 s capital of texas hwy nb
## 5 2901 S CAPITAL OF TEXAS HWY NB 2901 s capital of texas hwy nb</code></pre>
<pre class="r"><code>address_sample &lt;- merged_data_3 %&gt;% filter(`Zip Code` == 78746) %&gt;% 
    mutate(address_low = str_to_lower(Address)) %&gt;% select(Address, 
    address_low) %&gt;% head(1)

str_detect(address_sample, &quot;a&quot;)</code></pre>
<pre><code>## [1] FALSE  TRUE</code></pre>
<p>Using string r I converted the addresses in the zipcode 78746 to lower case, and saved them as a variable “address_low” then I used str_detect to see if the first address had a lowercase “a”. It returned false for the addresses I hadn’t converted and true for address_low.</p>
<pre class="r"><code>library(gt)
crime_no_dup %&gt;% group_by(`Zip Code`, `Location Type`) %&gt;% summarize(count = n()) %&gt;% 
    gt()</code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#faahmetsxs .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#faahmetsxs .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#faahmetsxs .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#faahmetsxs .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#faahmetsxs .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#faahmetsxs .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#faahmetsxs .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#faahmetsxs .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#faahmetsxs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#faahmetsxs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#faahmetsxs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#faahmetsxs .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#faahmetsxs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#faahmetsxs .gt_from_md > :first-child {
  margin-top: 0;
}

#faahmetsxs .gt_from_md > :last-child {
  margin-bottom: 0;
}

#faahmetsxs .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#faahmetsxs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#faahmetsxs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#faahmetsxs .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#faahmetsxs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#faahmetsxs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#faahmetsxs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#faahmetsxs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#faahmetsxs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#faahmetsxs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#faahmetsxs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#faahmetsxs .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#faahmetsxs .gt_left {
  text-align: left;
}

#faahmetsxs .gt_center {
  text-align: center;
}

#faahmetsxs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#faahmetsxs .gt_font_normal {
  font-weight: normal;
}

#faahmetsxs .gt_font_bold {
  font-weight: bold;
}

#faahmetsxs .gt_font_italic {
  font-style: italic;
}

#faahmetsxs .gt_super {
  font-size: 65%;
}

#faahmetsxs .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="faahmetsxs" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Location Type</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">count</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78617</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AMUSEMENT PARK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ARENA / STADIUM / FAIRGROUNDS / COLISEUM</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">INDUSTRIAL SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">JAIL / PRISON</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">26</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">14</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">302</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">98</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78652</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78653</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FARM FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">48</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">21</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78660</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">INDUSTRIAL SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">14</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">77</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">50</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78701</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">86</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">48</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">16</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">23</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">124</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">28</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">167</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">74</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">39</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHELTER-MISSION / HOMELESS</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">771</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRIBAL LANDS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78702</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AMUSEMENT PARK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">15</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">25</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">25</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">14</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">138</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">37</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">134</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">801</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">39</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHELTER-MISSION / HOMELESS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">871</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78703</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">81</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">64</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">319</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">16</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">254</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78704</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AMUSEMENT PARK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">13</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">14</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">44</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">13</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">15</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DOCK / WHARF / FREIGHT / MODAL TERMINAL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">12</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">19</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">JAIL / PRISON</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">188</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">37</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">193</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">933</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">58</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHELTER-MISSION / HOMELESS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">639</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">15</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78705</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ATM SEPARATE FROM BANK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">14</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">18</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">71</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">100</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">378</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">26</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">261</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78717</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ARENA / STADIUM / FAIRGROUNDS / COLISEUM</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">22</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">121</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">62</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78719</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">MILITARY INSTALLATION</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">12</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">40</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">43</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78721</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">36</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">27</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">371</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">280</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78722</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">28</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">18</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">148</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">165</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78723</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">22</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">24</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">19</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">12</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">116</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">97</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">798</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">REST AREA</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">20</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">13</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">509</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78724</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">JAIL / PRISON</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">46</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">18</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">521</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">272</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78725</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">JAIL / PRISON</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">40</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">29</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78726</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">75</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">27</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78727</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ARENA / STADIUM / FAIRGROUNDS / COLISEUM</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAMBLING FACILITY / CASINO / RACE TRACK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">INDUSTRIAL SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">50</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">29</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">405</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">137</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78728</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">13</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78729</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ATM SEPARATE FROM BANK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">40</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">36</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">241</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">94</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78730</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">INDUSTRIAL SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">31</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">21</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78731</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">19</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LAKE / WATERWAY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">40</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">43</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">272</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">137</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78732</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78733</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78734</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78735</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">28</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">22</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">147</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">89</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78736</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">12</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">72</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">18</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78737</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78738</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78739</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">JAIL / PRISON</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">15</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">176</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">21</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78741</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ATM SEPARATE FROM BANK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">16</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">15</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">18</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DOCK / WHARF / FREIGHT / MODAL TERMINAL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAMBLING FACILITY / CASINO / RACE TRACK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">18</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">28</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LAKE / WATERWAY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">87</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">145</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">709</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">28</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">621</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78742</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">26</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">16</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78744</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ARENA / STADIUM / FAIRGROUNDS / COLISEUM</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">28</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAMBLING FACILITY / CASINO / RACE TRACK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">25</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">INDUSTRIAL SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LAKE / WATERWAY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">125</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">14</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">115</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">1167</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">REST AREA</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">16</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">626</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">15</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78745</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ATM SEPARATE FROM BANK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">18</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">41</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">19</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">22</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAMBLING FACILITY / CASINO / RACE TRACK</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">20</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">157</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">15</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">150</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">1426</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">32</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHELTER-MISSION / HOMELESS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">626</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78746</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ARENA / STADIUM / FAIRGROUNDS / COLISEUM</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">12</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DOCK / WHARF / FREIGHT / MODAL TERMINAL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LAKE / WATERWAY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">40</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">45</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">38</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">189</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">109</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78747</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">13</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">32</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">322</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">77</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78748</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AMUSEMENT PARK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ATM SEPARATE FROM BANK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">12</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">84</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">49</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">872</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">220</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78749</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ATM SEPARATE FROM BANK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">55</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">43</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">499</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">131</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78750</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">60</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">12</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">33</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">349</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">93</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78751</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ATM SEPARATE FROM BANK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">13</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">INDUSTRIAL SITE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">46</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">46</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">335</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHELTER-MISSION / HOMELESS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">217</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78752</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">20</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">27</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">INDUSTRIAL SITE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">60</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">82</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">380</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">21</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">427</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRIBAL LANDS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">14</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78753</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AMUSEMENT PARK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ATM SEPARATE FROM BANK</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CAMP / CAMPGROUND</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">36</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">12</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">15</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">25</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DOCK / WHARF / FREIGHT / MODAL TERMINAL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAMBLING FACILITY / CASINO / RACE TRACK</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">16</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">53</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">INDUSTRIAL SITE</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">136</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">167</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">905</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">27</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">666</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">12</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78754</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">INDUSTRIAL SITE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">64</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">28</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">271</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">112</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78756</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">26</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">23</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">132</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">13</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">86</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78757</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AMUSEMENT PARK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ATM SEPARATE FROM BANK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">41</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">105</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">82</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">521</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">21</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOLS / COLLEGES</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">20</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">179</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78758</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ARENA / STADIUM / FAIRGROUNDS / COLISEUM</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">57</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMUNITY CENTER</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">14</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DAYCARE FACILITY</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">17</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">FIELD / WOODS</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAMBLING FACILITY / CASINO / RACE TRACK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">19</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">INDUSTRIAL SITE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">182</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">13</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">187</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">951</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">38</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHELTER-MISSION / HOMELESS</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">15</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">577</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">9</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">78759</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ABANDONED/CONDEMNED STRUCTURE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">ATM SEPARATE FROM BANK</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">AUTO DEALERSHIP NEW / USED</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BANKS / SAVINGS &amp; LOAN</td>
      <td class="gt_row gt_center">8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">BAR / NIGHT CLUB</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CHURCH / SYNAGOGUE / TEMPLE / MOSQUE</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">COMMERCIAL / OFFICE BUILDING</td>
      <td class="gt_row gt_center">26</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONSTRUCTION SITE</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">CONVENIENCE STORE</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DEPARTMENT / DISCOUNT STORE</td>
      <td class="gt_row gt_center">24</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">DRUG STORE / DR. OFFICE / HOSPITAL</td>
      <td class="gt_row gt_center">10</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GAS / SERVICE STATIONS</td>
      <td class="gt_row gt_center">7</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GOVERNMENT / PUBLIC BUILDING</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">GROCERY / SUPERMARKET</td>
      <td class="gt_row gt_center">6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">HOTEL / MOTEL / ETC.</td>
      <td class="gt_row gt_center">14</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">JAIL / PRISON</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">LIQUOR STORE</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">OTHER / UNKNOWN</td>
      <td class="gt_row gt_center">86</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARK / PLAYGROUND</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">PARKING LOTS / GARAGE</td>
      <td class="gt_row gt_center">104</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RENTAL STORAGE FACILITY</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESIDENCE / HOME</td>
      <td class="gt_row gt_center">465</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">REST AREA</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">RESTAURANTS</td>
      <td class="gt_row gt_center">24</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - COLLEGE / UNIVERSITY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SCHOOL - ELEMENTARY / SECONDARY</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SHOPPING MALL</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">SPECIALTY  STORE (TV  FUR ETC.)</td>
      <td class="gt_row gt_center">5</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">STREETS / HWY / ROAD / ALLEY</td>
      <td class="gt_row gt_center">237</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)</td>
      <td class="gt_row gt_center">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_center">11</td>
    </tr>
  </tbody>
  
  
</table></div>
<pre class="r"><code># Reshape tables
table1 &lt;- crime_no_dup %&gt;% group_by(`Zip Code`) %&gt;% summarize(mean_schools = mean(numOfPrimarySchools + 
    numOfElementarySchools + numOfHighSchools + numOfMiddleSchools)) %&gt;% 
    pivot_wider(names_from = `Zip Code`, values_from = mean_schools)
table1</code></pre>
<pre><code>## # A tibble: 1 x 47
##   `78617` `78652` `78653` `78660` `78701` `78702` `78703` `78704` `78705`
##     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1       3       2       3       3       3       3       3       3       3
## # … with 38 more variables: `78717` &lt;dbl&gt;, `78719` &lt;dbl&gt;, `78721` &lt;dbl&gt;,
## #   `78722` &lt;dbl&gt;, `78723` &lt;dbl&gt;, `78724` &lt;dbl&gt;, `78725` &lt;dbl&gt;, `78726` &lt;dbl&gt;,
## #   `78727` &lt;dbl&gt;, `78728` &lt;dbl&gt;, `78729` &lt;dbl&gt;, `78730` &lt;dbl&gt;, `78731` &lt;dbl&gt;,
## #   `78732` &lt;dbl&gt;, `78733` &lt;dbl&gt;, `78734` &lt;dbl&gt;, `78735` &lt;dbl&gt;, `78736` &lt;dbl&gt;,
## #   `78737` &lt;dbl&gt;, `78738` &lt;dbl&gt;, `78739` &lt;dbl&gt;, `78741` &lt;dbl&gt;, `78742` &lt;dbl&gt;,
## #   `78744` &lt;dbl&gt;, `78745` &lt;dbl&gt;, `78746` &lt;dbl&gt;, `78747` &lt;dbl&gt;, `78748` &lt;dbl&gt;,
## #   `78749` &lt;dbl&gt;, `78750` &lt;dbl&gt;, `78751` &lt;dbl&gt;, `78752` &lt;dbl&gt;, `78753` &lt;dbl&gt;,
## #   `78754` &lt;dbl&gt;, `78756` &lt;dbl&gt;, `78757` &lt;dbl&gt;, `78758` &lt;dbl&gt;, `78759` &lt;dbl&gt;</code></pre>
<p>Lastly I summarized the crime statistics overall in terms of the mean, standard deviation, variance, maximum and minimum, as well as, count. I wanted to see areas downtown and what crime stats were here, which was interesting as it revealed in 78701 a lot of crime was around bar and night clubs, parking lots, as well as streets. I used pivot_wider to arrange the summary statistics here for Zip Code and location type which broke down th most common location in which crime occurred in certain areas. I also arranged a table for statistics which showed the number of public schools in each zip code it uses pivot wider to create the summary statistics, the areas with the highest areas of schools were 78753 and 78754.</p>
</div>
<div id="visualizing" class="section level4">
<h4>Visualizing</h4>
<pre class="r"><code>library(ggplot2)
crime_daily = crime_no_dup %&gt;% group_by(`Council District`, `Incident Number`)
crime_count = summarize(crime_daily) %&gt;% count()
ggplot(crime_count, aes(x = `Council District`, y = n)) + geom_point(colour = &quot;red&quot;) + 
    geom_line(colour = &quot;red&quot;, size = 1.5) + theme_light(base_size = 12) + 
    xlab(&quot;Coucil District&quot;) + ylab(&quot;Count of indicents&quot;) + scale_x_continuous(breaks = c(1:10)) + 
    ggtitle(&quot;The Number of Incidents in Austin Council Districts&quot;) + 
    theme(plot.title = element_text(size = 16))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" /> In this project, I analyzed the crime incident data from the year of 2018 for the city of Austin. The first visualization is a graphical representation of the relationship between the variables for the incident reports and Austin City Council Districts. It can be find the place with the greatest amount of incident reports, is District 1, or far East Austin, and the place with the least is District 6, or far Northwest Austin. Overall the trend of the graph seems to prove that whether North or South, the most dangerous neighborhoods in Austin are within East Austin, and i-35 is somewhat of the dividing line.</p>
<pre class="r"><code>library(ggplot2)
merged_data_3 %&gt;% group_by(`Council District`) %&gt;% summarize(average_price = mean(latestPrice)) %&gt;% 
    na.omit() %&gt;% ggplot(merged_data_3, mapping = aes(x = `Council District`, 
    y = average_price)) + geom_bar(stat = &quot;identity&quot;) + scale_x_continuous(breaks = c(1, 
    2, 3, 4, 5, 6, 7, 8, 9, 10))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>This bar graph of the recent listings values of sold properties around Austin sorted by the Austin City Council Districts shows that the areas with generally higher home values have been safer if we look back to the graph that analyzed the crime incident data and compare districts. This could potentially show that higher crime rates can decrease the proprety values in an area. Another observation which can be made within the City Council District 9, where UT Austin is located, there are the highest average listing sale prices in Austin.</p>
<pre class="r"><code>library(ggplot2)
category_count = crime_no_dup %&gt;% group_by(`Category Description`) %&gt;% 
    count()
crime_no_dup %&gt;% drop_na() %&gt;% ggplot(crime_no_dup, mapping = aes(x = frequency(category_count), 
    y = `Category Description`)) + geom_col() + xlab(&quot;Frequency&quot;) + 
    ggtitle(&quot;Freqeuncies of Different types of Crime in Austin 2018&quot;) + 
    theme(plot.title = element_text(size = 16))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>This bar graph has bars which represent the overall amount of crime in Austin in the year 2018 in different categories, using the crime dataset and removing the many NAs. From the available data that had been categorized it seems theft was the most common crime by far. Following general theft, are the categories for crime of burglary and auto-theft.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
